version: '3.7'

networks:
  proxy_net:
    name: proxy_net
    external: true

services:
  surveyor:
    build:
      context: .
      dockerfile: Dockerfile.flaskapp
    image: flaskapp:latest
    environment:
      PYTHONPATH: /srv
      FLASK_APP: app.py
      FLASK_ENV: production
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      VIRTUAL_HOST: webforms.co.clatsop.or.us
      VIRTUAL_PORT: 5000
      NETWORK_ACCESS: internal
      LETSENCRYPT_HOST: webforms.co.clatsop.or.us
      LETSENCRYPT_MAIL: bwilson@co.clatsop.or.us
    command: ["flask", "run"]
    volumes:
      - .:/srv
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    user: app
    networks:
      proxy_net:
        aliases:
          - webforms
    # proxy will not work without this
    ports:
      - "5000:5000"
    # for compose
    restart: unless-stopped